server:
  port: 8080
spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/staging
    username: root
    password: root
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
